package com.microsoft.schemas.dynamics._2008._01.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2013-03-20T13:23:21.171+01:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://schemas.microsoft.com/dynamics/2008/01/services", name = "CustomerService")
@XmlSeeAlso({com.microsoft.schemas.dynamics._2006._02.documents.entitykeylist.ObjectFactory.class, com.microsoft.schemas.dynamics._2010._01.datacontracts.ObjectFactory.class, com.microsoft.schemas.dynamics._2006._02.documents.querycriteria.ObjectFactory.class, com.microsoft.schemas.dynamics._2006._02.documents.entitykey.ObjectFactory.class, com.microsoft.schemas.dynamics._2008._01.documents.customer.ObjectFactory.class, com.microsoft.schemas.dynamics._2008._01.documents.fault.ObjectFactory.class, com.microsoft.schemas.dynamics._2008._01.sharedtypes.ObjectFactory.class, ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, generated.ObjectFactory.class, org.datacontract.schemas._2004._07.microsoft_dynamics_ax_framework.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CustomerService {

    @WebResult(name = "CustomerServiceCreateResponse", targetNamespace = "http://schemas.microsoft.com/dynamics/2008/01/services", partName = "parameters")
    @Action(input = "http://schemas.microsoft.com/dynamics/2008/01/services/CustomerService/create", output = "http://schemas.microsoft.com/dynamics/2008/01/services/CustomerService/createResponse", fault = {@FaultAction(className = CustomerServiceCreateAifFaultFaultFaultMessage.class, value = "http://schemas.microsoft.com/dynamics/2008/01/services/CustomerService/createAifFaultFault")})
    @WebMethod(action = "http://schemas.microsoft.com/dynamics/2008/01/services/CustomerService/create")
    public CustomerServiceCreateResponse create(
        @WebParam(partName = "parameters", name = "CustomerServiceCreateRequest", targetNamespace = "http://schemas.microsoft.com/dynamics/2008/01/services")
        CustomerServiceCreateRequest parameters,
        @WebParam(partName = "context", name = "CallContext", targetNamespace = "http://schemas.microsoft.com/dynamics/2010/01/datacontracts", header = true)
        com.microsoft.schemas.dynamics._2010._01.datacontracts.CallContext context
    ) throws CustomerServiceCreateAifFaultFaultFaultMessage;

    @WebResult(name = "CustomerServiceFindResponse", targetNamespace = "http://schemas.microsoft.com/dynamics/2008/01/services", partName = "parameters")
    @Action(input = "http://schemas.microsoft.com/dynamics/2008/01/services/CustomerService/find", output = "http://schemas.microsoft.com/dynamics/2008/01/services/CustomerService/findResponse", fault = {@FaultAction(className = CustomerServiceFindAifFaultFaultFaultMessage.class, value = "http://schemas.microsoft.com/dynamics/2008/01/services/CustomerService/findAifFaultFault")})
    @WebMethod(action = "http://schemas.microsoft.com/dynamics/2008/01/services/CustomerService/find")
    public CustomerServiceFindResponse find(
        @WebParam(partName = "parameters", name = "CustomerServiceFindRequest", targetNamespace = "http://schemas.microsoft.com/dynamics/2008/01/services")
        CustomerServiceFindRequest parameters,
        @WebParam(partName = "context", name = "CallContext", targetNamespace = "http://schemas.microsoft.com/dynamics/2010/01/datacontracts", header = true)
        com.microsoft.schemas.dynamics._2010._01.datacontracts.CallContext context
    ) throws CustomerServiceFindAifFaultFaultFaultMessage;

    @WebResult(name = "CustomerServiceReadResponse", targetNamespace = "http://schemas.microsoft.com/dynamics/2008/01/services", partName = "parameters")
    @Action(input = "http://schemas.microsoft.com/dynamics/2008/01/services/CustomerService/read", output = "http://schemas.microsoft.com/dynamics/2008/01/services/CustomerService/readResponse", fault = {@FaultAction(className = CustomerServiceReadAifFaultFaultFaultMessage.class, value = "http://schemas.microsoft.com/dynamics/2008/01/services/CustomerService/readAifFaultFault")})
    @WebMethod(action = "http://schemas.microsoft.com/dynamics/2008/01/services/CustomerService/read")
    public CustomerServiceReadResponse read(
        @WebParam(partName = "parameters", name = "CustomerServiceReadRequest", targetNamespace = "http://schemas.microsoft.com/dynamics/2008/01/services")
        CustomerServiceReadRequest parameters,
        @WebParam(partName = "context", name = "CallContext", targetNamespace = "http://schemas.microsoft.com/dynamics/2010/01/datacontracts", header = true)
        com.microsoft.schemas.dynamics._2010._01.datacontracts.CallContext context
    ) throws CustomerServiceReadAifFaultFaultFaultMessage;

    @WebResult(name = "CustomerServiceUpdateResponse", targetNamespace = "http://schemas.microsoft.com/dynamics/2008/01/services", partName = "parameters")
    @Action(input = "http://schemas.microsoft.com/dynamics/2008/01/services/CustomerService/update", output = "http://schemas.microsoft.com/dynamics/2008/01/services/CustomerService/updateResponse", fault = {@FaultAction(className = CustomerServiceUpdateAifFaultFaultFaultMessage.class, value = "http://schemas.microsoft.com/dynamics/2008/01/services/CustomerService/updateAifFaultFault")})
    @WebMethod(action = "http://schemas.microsoft.com/dynamics/2008/01/services/CustomerService/update")
    public CustomerServiceUpdateResponse update(
        @WebParam(partName = "parameters", name = "CustomerServiceUpdateRequest", targetNamespace = "http://schemas.microsoft.com/dynamics/2008/01/services")
        CustomerServiceUpdateRequest parameters,
        @WebParam(partName = "context", name = "CallContext", targetNamespace = "http://schemas.microsoft.com/dynamics/2010/01/datacontracts", header = true)
        com.microsoft.schemas.dynamics._2010._01.datacontracts.CallContext context
    ) throws CustomerServiceUpdateAifFaultFaultFaultMessage;
}
