package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2013-03-20T13:23:17.940+01:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://tempuri.org", name = "MDS_ITGSalesClAService")
@XmlSeeAlso({ObjectFactory.class, com.microsoft.schemas.dynamics._2010._01.datacontracts.ObjectFactory.class, com.microsoft.schemas.dynamics._2006._02.documents.querycriteria.ObjectFactory.class, com.microsoft.schemas.dynamics._2006._02.documents.entitykeylist.ObjectFactory.class, com.microsoft.schemas.dynamics._2006._02.documents.entitykey.ObjectFactory.class, com.microsoft.schemas.dynamics._2008._01.documents.fault.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, com.microsoft.schemas.dynamics._2008._01.sharedtypes.ObjectFactory.class, generated.ObjectFactory.class, com.microsoft.schemas.dynamics._2008._01.documents.mds_itgsalescla.ObjectFactory.class, org.datacontract.schemas._2004._07.microsoft_dynamics_ax_framework.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MDSITGSalesClAService {

    @WebResult(name = "MDS_ITGSalesClAServiceFindResponse", targetNamespace = "http://tempuri.org", partName = "parameters")
    @Action(input = "http://tempuri.org/MDS_ITGSalesClAService/find", output = "http://tempuri.org/MDS_ITGSalesClAService/findResponse", fault = {@FaultAction(className = MDSITGSalesClAServiceFindAifFaultFaultFaultMessage.class, value = "http://tempuri.org/MDS_ITGSalesClAService/findAifFaultFault")})
    @WebMethod(action = "http://tempuri.org/MDS_ITGSalesClAService/find")
    public MDSITGSalesClAServiceFindResponse find(
        @WebParam(partName = "parameters", name = "MDS_ITGSalesClAServiceFindRequest", targetNamespace = "http://tempuri.org")
        MDSITGSalesClAServiceFindRequest parameters,
        @WebParam(partName = "context", name = "CallContext", targetNamespace = "http://schemas.microsoft.com/dynamics/2010/01/datacontracts", header = true)
        com.microsoft.schemas.dynamics._2010._01.datacontracts.CallContext context
    ) throws MDSITGSalesClAServiceFindAifFaultFaultFaultMessage;

    @WebResult(name = "MDS_ITGSalesClAServiceReadResponse", targetNamespace = "http://tempuri.org", partName = "parameters")
    @Action(input = "http://tempuri.org/MDS_ITGSalesClAService/read", output = "http://tempuri.org/MDS_ITGSalesClAService/readResponse", fault = {@FaultAction(className = MDSITGSalesClAServiceReadAifFaultFaultFaultMessage.class, value = "http://tempuri.org/MDS_ITGSalesClAService/readAifFaultFault")})
    @WebMethod(action = "http://tempuri.org/MDS_ITGSalesClAService/read")
    public MDSITGSalesClAServiceReadResponse read(
        @WebParam(partName = "parameters", name = "MDS_ITGSalesClAServiceReadRequest", targetNamespace = "http://tempuri.org")
        MDSITGSalesClAServiceReadRequest parameters,
        @WebParam(partName = "context", name = "CallContext", targetNamespace = "http://schemas.microsoft.com/dynamics/2010/01/datacontracts", header = true)
        com.microsoft.schemas.dynamics._2010._01.datacontracts.CallContext context
    ) throws MDSITGSalesClAServiceReadAifFaultFaultFaultMessage;

    @WebResult(name = "MDS_ITGSalesClAServiceUpdateResponse", targetNamespace = "http://tempuri.org", partName = "parameters")
    @Action(input = "http://tempuri.org/MDS_ITGSalesClAService/update", output = "http://tempuri.org/MDS_ITGSalesClAService/updateResponse", fault = {@FaultAction(className = MDSITGSalesClAServiceUpdateAifFaultFaultFaultMessage.class, value = "http://tempuri.org/MDS_ITGSalesClAService/updateAifFaultFault")})
    @WebMethod(action = "http://tempuri.org/MDS_ITGSalesClAService/update")
    public MDSITGSalesClAServiceUpdateResponse update(
        @WebParam(partName = "parameters", name = "MDS_ITGSalesClAServiceUpdateRequest", targetNamespace = "http://tempuri.org")
        MDSITGSalesClAServiceUpdateRequest parameters,
        @WebParam(partName = "context", name = "CallContext", targetNamespace = "http://schemas.microsoft.com/dynamics/2010/01/datacontracts", header = true)
        com.microsoft.schemas.dynamics._2010._01.datacontracts.CallContext context
    ) throws MDSITGSalesClAServiceUpdateAifFaultFaultFaultMessage;

    @WebResult(name = "MDS_ITGSalesClAServiceCreateResponse", targetNamespace = "http://tempuri.org", partName = "parameters")
    @Action(input = "http://tempuri.org/MDS_ITGSalesClAService/create", output = "http://tempuri.org/MDS_ITGSalesClAService/createResponse", fault = {@FaultAction(className = MDSITGSalesClAServiceCreateAifFaultFaultFaultMessage.class, value = "http://tempuri.org/MDS_ITGSalesClAService/createAifFaultFault")})
    @WebMethod(action = "http://tempuri.org/MDS_ITGSalesClAService/create")
    public MDSITGSalesClAServiceCreateResponse create(
        @WebParam(partName = "parameters", name = "MDS_ITGSalesClAServiceCreateRequest", targetNamespace = "http://tempuri.org")
        MDSITGSalesClAServiceCreateRequest parameters,
        @WebParam(partName = "context", name = "CallContext", targetNamespace = "http://schemas.microsoft.com/dynamics/2010/01/datacontracts", header = true)
        com.microsoft.schemas.dynamics._2010._01.datacontracts.CallContext context
    ) throws MDSITGSalesClAServiceCreateAifFaultFaultFaultMessage;
}
