package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2013-03-20T13:23:23.545+01:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://tempuri.org", name = "MDS_ITGCustBankService")
@XmlSeeAlso({ObjectFactory.class, com.microsoft.schemas.dynamics._2006._02.documents.querycriteria.ObjectFactory.class, com.microsoft.schemas.dynamics._2006._02.documents.entitykeylist.ObjectFactory.class, com.microsoft.schemas.dynamics._2010._01.datacontracts.ObjectFactory.class, com.microsoft.schemas.dynamics._2006._02.documents.entitykey.ObjectFactory.class, com.microsoft.schemas.dynamics._2008._01.documents.fault.ObjectFactory.class, com.microsoft.schemas.dynamics._2008._01.sharedtypes.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, generated.ObjectFactory.class, com.microsoft.schemas.dynamics._2008._01.documents.mds_itgcustbank.ObjectFactory.class, org.datacontract.schemas._2004._07.microsoft_dynamics_ax_framework.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MDSITGCustBankService {

    @WebResult(name = "MDS_ITGCustBankServiceFindResponse", targetNamespace = "http://tempuri.org", partName = "parameters")
    @Action(input = "http://tempuri.org/MDS_ITGCustBankService/find", output = "http://tempuri.org/MDS_ITGCustBankService/findResponse", fault = {@FaultAction(className = MDSITGCustBankServiceFindAifFaultFaultFaultMessage.class, value = "http://tempuri.org/MDS_ITGCustBankService/findAifFaultFault")})
    @WebMethod(action = "http://tempuri.org/MDS_ITGCustBankService/find")
    public MDSITGCustBankServiceFindResponse find(
        @WebParam(partName = "parameters", name = "MDS_ITGCustBankServiceFindRequest", targetNamespace = "http://tempuri.org")
        MDSITGCustBankServiceFindRequest parameters,
        @WebParam(partName = "context", name = "CallContext", targetNamespace = "http://schemas.microsoft.com/dynamics/2010/01/datacontracts", header = true)
        com.microsoft.schemas.dynamics._2010._01.datacontracts.CallContext context
    ) throws MDSITGCustBankServiceFindAifFaultFaultFaultMessage;

    @WebResult(name = "MDS_ITGCustBankServiceReadResponse", targetNamespace = "http://tempuri.org", partName = "parameters")
    @Action(input = "http://tempuri.org/MDS_ITGCustBankService/read", output = "http://tempuri.org/MDS_ITGCustBankService/readResponse", fault = {@FaultAction(className = MDSITGCustBankServiceReadAifFaultFaultFaultMessage.class, value = "http://tempuri.org/MDS_ITGCustBankService/readAifFaultFault")})
    @WebMethod(action = "http://tempuri.org/MDS_ITGCustBankService/read")
    public MDSITGCustBankServiceReadResponse read(
        @WebParam(partName = "parameters", name = "MDS_ITGCustBankServiceReadRequest", targetNamespace = "http://tempuri.org")
        MDSITGCustBankServiceReadRequest parameters,
        @WebParam(partName = "context", name = "CallContext", targetNamespace = "http://schemas.microsoft.com/dynamics/2010/01/datacontracts", header = true)
        com.microsoft.schemas.dynamics._2010._01.datacontracts.CallContext context
    ) throws MDSITGCustBankServiceReadAifFaultFaultFaultMessage;

    @WebResult(name = "MDS_ITGCustBankServiceUpdateResponse", targetNamespace = "http://tempuri.org", partName = "parameters")
    @Action(input = "http://tempuri.org/MDS_ITGCustBankService/update", output = "http://tempuri.org/MDS_ITGCustBankService/updateResponse", fault = {@FaultAction(className = MDSITGCustBankServiceUpdateAifFaultFaultFaultMessage.class, value = "http://tempuri.org/MDS_ITGCustBankService/updateAifFaultFault")})
    @WebMethod(action = "http://tempuri.org/MDS_ITGCustBankService/update")
    public MDSITGCustBankServiceUpdateResponse update(
        @WebParam(partName = "parameters", name = "MDS_ITGCustBankServiceUpdateRequest", targetNamespace = "http://tempuri.org")
        MDSITGCustBankServiceUpdateRequest parameters,
        @WebParam(partName = "context", name = "CallContext", targetNamespace = "http://schemas.microsoft.com/dynamics/2010/01/datacontracts", header = true)
        com.microsoft.schemas.dynamics._2010._01.datacontracts.CallContext context
    ) throws MDSITGCustBankServiceUpdateAifFaultFaultFaultMessage;

    @WebResult(name = "MDS_ITGCustBankServiceCreateResponse", targetNamespace = "http://tempuri.org", partName = "parameters")
    @Action(input = "http://tempuri.org/MDS_ITGCustBankService/create", output = "http://tempuri.org/MDS_ITGCustBankService/createResponse", fault = {@FaultAction(className = MDSITGCustBankServiceCreateAifFaultFaultFaultMessage.class, value = "http://tempuri.org/MDS_ITGCustBankService/createAifFaultFault")})
    @WebMethod(action = "http://tempuri.org/MDS_ITGCustBankService/create")
    public MDSITGCustBankServiceCreateResponse create(
        @WebParam(partName = "parameters", name = "MDS_ITGCustBankServiceCreateRequest", targetNamespace = "http://tempuri.org")
        MDSITGCustBankServiceCreateRequest parameters,
        @WebParam(partName = "context", name = "CallContext", targetNamespace = "http://schemas.microsoft.com/dynamics/2010/01/datacontracts", header = true)
        com.microsoft.schemas.dynamics._2010._01.datacontracts.CallContext context
    ) throws MDSITGCustBankServiceCreateAifFaultFaultFaultMessage;
}
