
package org.tempuri;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import com.tradedoubler.webservice.routing.salesorderbasisline.RoutingService;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2013-03-20T13:23:28.745+01:00
 * Generated source version: 2.6.1
 * 
 */
public final class MDSSalesOrderBasisLineService_BasicHttpBindingMDSSalesOrderBasisLineService_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "RoutingService");

    private MDSSalesOrderBasisLineService_BasicHttpBindingMDSSalesOrderBasisLineService_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RoutingService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RoutingService ss = new RoutingService(wsdlURL, SERVICE_NAME);
        MDSSalesOrderBasisLineService port = ss.getBasicHttpBindingMDSSalesOrderBasisLineService();  
        
        {
        System.out.println("Invoking orderBasisLineInbound...");
        org.tempuri.MDSSalesOrderBasisLineServiceOrderBasisLineInboundRequest _orderBasisLineInbound_parameters = null;
        com.microsoft.schemas.dynamics._2010._01.datacontracts.CallContext _orderBasisLineInbound_context = null;
        try {
            org.tempuri.MDSSalesOrderBasisLineServiceOrderBasisLineInboundResponse _orderBasisLineInbound__return = port.orderBasisLineInbound(_orderBasisLineInbound_parameters, _orderBasisLineInbound_context);
            System.out.println("orderBasisLineInbound.result=" + _orderBasisLineInbound__return);

        } catch (MDSSalesOrderBasisLineServiceOrderBasisLineInboundAifFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: MDS_SalesOrderBasisLineService_orderBasisLineInbound_AifFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
