package com.microsoft.schemas.netfx._2009._05.routing;

import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2013-03-20T13:23:29.125+01:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://schemas.microsoft.com/netfx/2009/05/routing", name = "IRequestReplyRouter")
@XmlSeeAlso({mds_salesorderbasisline.ObjectFactory.class, com.microsoft.schemas.dynamics._2010._01.datacontracts.ObjectFactory.class, com.microsoft.schemas.dynamics._2008._01.documents.fault.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, org.datacontract.schemas._2004._07.microsoft_dynamics_ax_framework.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class})
public interface IRequestReplyRouter {
}
