//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.28 at 01:35:45 PM CET 
//


package com.tradedoubler.customerinvoice;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AxdEntity_MDS_SalesOrderBasisLine complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AxdEntity_MDS_SalesOrderBasisLine">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ClientAgreementSourceSystemAgreement" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_MDS_SalesSourceSystemAgreementId" minOccurs="0"/>
 *         &lt;element name="CostAmount" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_MDS_SalesOrderBasisLineCostAmount" minOccurs="0"/>
 *         &lt;element name="CreditedInvoiceId" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_MDS_SalesOrderBasisLineCreditedInvoiceId" minOccurs="0"/>
 *         &lt;element name="DateOfPrepayment" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_MDS_SalesOrderBasisLineDateOfPrepayment" minOccurs="0"/>
 *         &lt;element name="Debit" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_MDS_SalesOrderBasisLineDebit" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_MDS_SalesOrderBasisLineDescription" minOccurs="0"/>
 *         &lt;element name="Invoiceable" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_MDS_SalesOrderBasisLineInvoiceable" minOccurs="0"/>
 *         &lt;element name="OrderBasisLineId" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_MDS_SalesOrderBasisLineId" minOccurs="0"/>
 *         &lt;element name="OrderItemId" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdUnion_AxdExtType_ItemId_AxdType_ExtCodeValue" minOccurs="0"/>
 *         &lt;element name="Period" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_MDS_SalesOrderBasisLinePeriod" minOccurs="0"/>
 *         &lt;element name="ProcessedAgreementCurrencyCode" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdUnion_AxdExtType_CurrencyCode_AxdType_ExtCodeValue" minOccurs="0"/>
 *         &lt;element name="ProcessedAgreementDataAreaId" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_MDS_SalesOrderBasisLineProcAgrDataAreaId" minOccurs="0"/>
 *         &lt;element name="ProcessedDataAreaId" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_MDS_SalesOrderBasisLineProcessedDataArea" minOccurs="0"/>
 *         &lt;element name="ProcessedIntercompanyHandled" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdEnum_NoYes" minOccurs="0"/>
 *         &lt;element name="ProcessedInvoiceRuleCurrencyCode" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdUnion_AxdExtType_CurrencyCode_AxdType_ExtCodeValue" minOccurs="0"/>
 *         &lt;element name="ProcessedInvoiceRuleRevenueTypeId" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_MDS_SalesRevenueTypeId" minOccurs="0"/>
 *         &lt;element name="ProcessedSalesId" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_SalesIdBase" minOccurs="0"/>
 *         &lt;element name="ProcessedSalesLineId" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_MDS_SalesOrderBasisLineProcessedLineId" minOccurs="0"/>
 *         &lt;element name="ProcessedStatus" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdEnum_MDS_SalesOrderBasisLineStatus" minOccurs="0"/>
 *         &lt;element name="Quantity" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_MDS_SalesOrderBasisLineQuantity" minOccurs="0"/>
 *         &lt;element name="RecId" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_RecId" minOccurs="0"/>
 *         &lt;element name="RecVersion" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_RecVersion" minOccurs="0"/>
 *         &lt;element name="SplitterValue" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_MDS_SalesSplitterValue" minOccurs="0"/>
 *         &lt;element name="TotalAmount" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_MDS_SalesOrderBasisLineTotalAmount" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="class" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" fixed="entity" />
 *       &lt;attribute name="action" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdEnum_AxdEntityAction" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AxdEntity_MDS_SalesOrderBasisLine", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", propOrder = {
    "clientAgreementSourceSystemAgreement",
    "costAmount",
    "creditedInvoiceId",
    "dateOfPrepayment",
    "debit",
    "description",
    "invoiceable",
    "orderBasisLineId",
    "orderItemId",
    "period",
    "processedAgreementCurrencyCode",
    "processedAgreementDataAreaId",
    "processedDataAreaId",
    "processedIntercompanyHandled",
    "processedInvoiceRuleCurrencyCode",
    "processedInvoiceRuleRevenueTypeId",
    "processedSalesId",
    "processedSalesLineId",
    "processedStatus",
    "quantity",
    "recId",
    "recVersion",
    "splitterValue",
    "totalAmount"
})
public class AxdEntityMDSSalesOrderBasisLine {

    @XmlElementRef(name = "ClientAgreementSourceSystemAgreement", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> clientAgreementSourceSystemAgreement;
    @XmlElementRef(name = "CostAmount", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<BigDecimal> costAmount;
    @XmlElementRef(name = "CreditedInvoiceId", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> creditedInvoiceId;
    @XmlElementRef(name = "DateOfPrepayment", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> dateOfPrepayment;
    @XmlElementRef(name = "Debit", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<AxdExtTypeMDSSalesOrderBasisLineDebit> debit;
    @XmlElementRef(name = "Description", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> description;
    @XmlElementRef(name = "Invoiceable", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<AxdExtTypeMDSSalesOrderBasisLineInvoiceable> invoiceable;
    @XmlElementRef(name = "OrderBasisLineId", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> orderBasisLineId;
    @XmlElementRef(name = "OrderItemId", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> orderItemId;
    @XmlElementRef(name = "Period", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> period;
    @XmlElementRef(name = "ProcessedAgreementCurrencyCode", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> processedAgreementCurrencyCode;
    @XmlElementRef(name = "ProcessedAgreementDataAreaId", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> processedAgreementDataAreaId;
    @XmlElementRef(name = "ProcessedDataAreaId", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> processedDataAreaId;
    @XmlElementRef(name = "ProcessedIntercompanyHandled", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<AxdEnumNoYes> processedIntercompanyHandled;
    @XmlElementRef(name = "ProcessedInvoiceRuleCurrencyCode", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> processedInvoiceRuleCurrencyCode;
    @XmlElementRef(name = "ProcessedInvoiceRuleRevenueTypeId", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> processedInvoiceRuleRevenueTypeId;
    @XmlElementRef(name = "ProcessedSalesId", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> processedSalesId;
    @XmlElementRef(name = "ProcessedSalesLineId", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<Long> processedSalesLineId;
    @XmlElementRef(name = "ProcessedStatus", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<AxdEnumMDSSalesOrderBasisLineStatus> processedStatus;
    @XmlElementRef(name = "Quantity", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<Integer> quantity;
    @XmlElementRef(name = "RecId", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<Long> recId;
    @XmlElementRef(name = "RecVersion", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<Integer> recVersion;
    @XmlElementRef(name = "SplitterValue", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> splitterValue;
    @XmlElementRef(name = "TotalAmount", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<BigDecimal> totalAmount;
    @XmlAttribute(name = "class", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String clazz;
    @XmlAttribute(name = "action")
    protected AxdEnumAxdEntityAction action;

    /**
     * Gets the value of the clientAgreementSourceSystemAgreement property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getClientAgreementSourceSystemAgreement() {
        return clientAgreementSourceSystemAgreement;
    }

    /**
     * Sets the value of the clientAgreementSourceSystemAgreement property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setClientAgreementSourceSystemAgreement(JAXBElement<String> value) {
        this.clientAgreementSourceSystemAgreement = value;
    }

    /**
     * Gets the value of the costAmount property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getCostAmount() {
        return costAmount;
    }

    /**
     * Sets the value of the costAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setCostAmount(JAXBElement<BigDecimal> value) {
        this.costAmount = value;
    }

    /**
     * Gets the value of the creditedInvoiceId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCreditedInvoiceId() {
        return creditedInvoiceId;
    }

    /**
     * Sets the value of the creditedInvoiceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCreditedInvoiceId(JAXBElement<String> value) {
        this.creditedInvoiceId = value;
    }

    /**
     * Gets the value of the dateOfPrepayment property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getDateOfPrepayment() {
        return dateOfPrepayment;
    }

    /**
     * Sets the value of the dateOfPrepayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setDateOfPrepayment(JAXBElement<XMLGregorianCalendar> value) {
        this.dateOfPrepayment = value;
    }

    /**
     * Gets the value of the debit property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AxdExtTypeMDSSalesOrderBasisLineDebit }{@code >}
     *     
     */
    public JAXBElement<AxdExtTypeMDSSalesOrderBasisLineDebit> getDebit() {
        return debit;
    }

    /**
     * Sets the value of the debit property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AxdExtTypeMDSSalesOrderBasisLineDebit }{@code >}
     *     
     */
    public void setDebit(JAXBElement<AxdExtTypeMDSSalesOrderBasisLineDebit> value) {
        this.debit = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDescription(JAXBElement<String> value) {
        this.description = value;
    }

    /**
     * Gets the value of the invoiceable property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AxdExtTypeMDSSalesOrderBasisLineInvoiceable }{@code >}
     *     
     */
    public JAXBElement<AxdExtTypeMDSSalesOrderBasisLineInvoiceable> getInvoiceable() {
        return invoiceable;
    }

    /**
     * Sets the value of the invoiceable property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AxdExtTypeMDSSalesOrderBasisLineInvoiceable }{@code >}
     *     
     */
    public void setInvoiceable(JAXBElement<AxdExtTypeMDSSalesOrderBasisLineInvoiceable> value) {
        this.invoiceable = value;
    }

    /**
     * Gets the value of the orderBasisLineId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getOrderBasisLineId() {
        return orderBasisLineId;
    }

    /**
     * Sets the value of the orderBasisLineId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setOrderBasisLineId(JAXBElement<String> value) {
        this.orderBasisLineId = value;
    }

    /**
     * Gets the value of the orderItemId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getOrderItemId() {
        return orderItemId;
    }

    /**
     * Sets the value of the orderItemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setOrderItemId(JAXBElement<String> value) {
        this.orderItemId = value;
    }

    /**
     * Gets the value of the period property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPeriod() {
        return period;
    }

    /**
     * Sets the value of the period property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPeriod(JAXBElement<String> value) {
        this.period = value;
    }

    /**
     * Gets the value of the processedAgreementCurrencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getProcessedAgreementCurrencyCode() {
        return processedAgreementCurrencyCode;
    }

    /**
     * Sets the value of the processedAgreementCurrencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setProcessedAgreementCurrencyCode(JAXBElement<String> value) {
        this.processedAgreementCurrencyCode = value;
    }

    /**
     * Gets the value of the processedAgreementDataAreaId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getProcessedAgreementDataAreaId() {
        return processedAgreementDataAreaId;
    }

    /**
     * Sets the value of the processedAgreementDataAreaId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setProcessedAgreementDataAreaId(JAXBElement<String> value) {
        this.processedAgreementDataAreaId = value;
    }

    /**
     * Gets the value of the processedDataAreaId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getProcessedDataAreaId() {
        return processedDataAreaId;
    }

    /**
     * Sets the value of the processedDataAreaId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setProcessedDataAreaId(JAXBElement<String> value) {
        this.processedDataAreaId = value;
    }

    /**
     * Gets the value of the processedIntercompanyHandled property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AxdEnumNoYes }{@code >}
     *     
     */
    public JAXBElement<AxdEnumNoYes> getProcessedIntercompanyHandled() {
        return processedIntercompanyHandled;
    }

    /**
     * Sets the value of the processedIntercompanyHandled property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AxdEnumNoYes }{@code >}
     *     
     */
    public void setProcessedIntercompanyHandled(JAXBElement<AxdEnumNoYes> value) {
        this.processedIntercompanyHandled = value;
    }

    /**
     * Gets the value of the processedInvoiceRuleCurrencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getProcessedInvoiceRuleCurrencyCode() {
        return processedInvoiceRuleCurrencyCode;
    }

    /**
     * Sets the value of the processedInvoiceRuleCurrencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setProcessedInvoiceRuleCurrencyCode(JAXBElement<String> value) {
        this.processedInvoiceRuleCurrencyCode = value;
    }

    /**
     * Gets the value of the processedInvoiceRuleRevenueTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getProcessedInvoiceRuleRevenueTypeId() {
        return processedInvoiceRuleRevenueTypeId;
    }

    /**
     * Sets the value of the processedInvoiceRuleRevenueTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setProcessedInvoiceRuleRevenueTypeId(JAXBElement<String> value) {
        this.processedInvoiceRuleRevenueTypeId = value;
    }

    /**
     * Gets the value of the processedSalesId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getProcessedSalesId() {
        return processedSalesId;
    }

    /**
     * Sets the value of the processedSalesId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setProcessedSalesId(JAXBElement<String> value) {
        this.processedSalesId = value;
    }

    /**
     * Gets the value of the processedSalesLineId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public JAXBElement<Long> getProcessedSalesLineId() {
        return processedSalesLineId;
    }

    /**
     * Sets the value of the processedSalesLineId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public void setProcessedSalesLineId(JAXBElement<Long> value) {
        this.processedSalesLineId = value;
    }

    /**
     * Gets the value of the processedStatus property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AxdEnumMDSSalesOrderBasisLineStatus }{@code >}
     *     
     */
    public JAXBElement<AxdEnumMDSSalesOrderBasisLineStatus> getProcessedStatus() {
        return processedStatus;
    }

    /**
     * Sets the value of the processedStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AxdEnumMDSSalesOrderBasisLineStatus }{@code >}
     *     
     */
    public void setProcessedStatus(JAXBElement<AxdEnumMDSSalesOrderBasisLineStatus> value) {
        this.processedStatus = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setQuantity(JAXBElement<Integer> value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the recId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public JAXBElement<Long> getRecId() {
        return recId;
    }

    /**
     * Sets the value of the recId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public void setRecId(JAXBElement<Long> value) {
        this.recId = value;
    }

    /**
     * Gets the value of the recVersion property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getRecVersion() {
        return recVersion;
    }

    /**
     * Sets the value of the recVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setRecVersion(JAXBElement<Integer> value) {
        this.recVersion = value;
    }

    /**
     * Gets the value of the splitterValue property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSplitterValue() {
        return splitterValue;
    }

    /**
     * Sets the value of the splitterValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSplitterValue(JAXBElement<String> value) {
        this.splitterValue = value;
    }

    /**
     * Gets the value of the totalAmount property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getTotalAmount() {
        return totalAmount;
    }

    /**
     * Sets the value of the totalAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setTotalAmount(JAXBElement<BigDecimal> value) {
        this.totalAmount = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClazz() {
        if (clazz == null) {
            return "entity";
        } else {
            return clazz;
        }
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClazz(String value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link AxdEnumAxdEntityAction }
     *     
     */
    public AxdEnumAxdEntityAction getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link AxdEnumAxdEntityAction }
     *     
     */
    public void setAction(AxdEnumAxdEntityAction value) {
        this.action = value;
    }

}
