//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.28 at 01:35:45 PM CET 
//


package com.tradedoubler.customerinvoice;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AxdEnum_HcmPersonMaritalStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AxdEnum_HcmPersonMaritalStatus">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="None"/>
 *     &lt;enumeration value="Married"/>
 *     &lt;enumeration value="Single"/>
 *     &lt;enumeration value="Widowed"/>
 *     &lt;enumeration value="Divorced"/>
 *     &lt;enumeration value="Cohabiting"/>
 *     &lt;enumeration value="RegisteredPartnership"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AxdEnum_HcmPersonMaritalStatus")
@XmlEnum
public enum AxdEnumHcmPersonMaritalStatus {

    @XmlEnumValue("None")
    NONE("None"),
    @XmlEnumValue("Married")
    MARRIED("Married"),
    @XmlEnumValue("Single")
    SINGLE("Single"),
    @XmlEnumValue("Widowed")
    WIDOWED("Widowed"),
    @XmlEnumValue("Divorced")
    DIVORCED("Divorced"),
    @XmlEnumValue("Cohabiting")
    COHABITING("Cohabiting"),
    @XmlEnumValue("RegisteredPartnership")
    REGISTERED_PARTNERSHIP("RegisteredPartnership");
    private final String value;

    AxdEnumHcmPersonMaritalStatus(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AxdEnumHcmPersonMaritalStatus fromValue(String v) {
        for (AxdEnumHcmPersonMaritalStatus c: AxdEnumHcmPersonMaritalStatus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
