//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.28 at 01:35:45 PM CET 
//


package com.tradedoubler.customerinvoice;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AxdEntity_CustInvoiceTrans complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AxdEntity_CustInvoiceTrans">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AmountDiscAmount" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_AmountCur" minOccurs="0"/>
 *         &lt;element name="AmountDiscPercentInclTax" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_AmountCur" minOccurs="0"/>
 *         &lt;element name="AssetBookId" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_AssetBookIdPurchSalesInvent" minOccurs="0"/>
 *         &lt;element name="AssetId" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_AssetIdOpen" minOccurs="0"/>
 *         &lt;element name="CommissAmountCur" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_CommissAmountCur" minOccurs="0"/>
 *         &lt;element name="CommissAmountMST" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_CommissAmountMST" minOccurs="0"/>
 *         &lt;element name="CommissCalc" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_CommissCalc" minOccurs="0"/>
 *         &lt;element name="CountryRegionOfShipment" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdUnion_AxdExtType_AddressCountryRegionId_AxdType_ExtCodeValue" minOccurs="0"/>
 *         &lt;element name="CurrencyCode" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdUnion_AxdExtType_CustCurrencyCode_AxdType_ExtCodeValue" minOccurs="0"/>
 *         &lt;element name="CustomerLineNum" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_CustLineNum" minOccurs="0"/>
 *         &lt;element name="DeliveryType" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_TradeLineDlvTypeId" minOccurs="0"/>
 *         &lt;element name="DiscAmount" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_SalesDiscAmount" minOccurs="0"/>
 *         &lt;element name="DiscPercent" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_SalesDiscPercent" minOccurs="0"/>
 *         &lt;element name="DlvDate" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_SalesShippingDate" minOccurs="0"/>
 *         &lt;element name="EInvoiceAccountCode" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_EInvoiceAccountCode" minOccurs="0"/>
 *         &lt;element name="ExternalItemId" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_SalesExternalItemId" minOccurs="0"/>
 *         &lt;element name="InterCompanyInventTransId" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_TradeInventTransId" minOccurs="0"/>
 *         &lt;element name="IntrastatDispatchId" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_IntrastatDispatchId" minOccurs="0"/>
 *         &lt;element name="InventDimId" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_InventDimId" minOccurs="0"/>
 *         &lt;element name="InventQty" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_InventQty" minOccurs="0"/>
 *         &lt;element name="InventRefId" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_InventRefId" minOccurs="0"/>
 *         &lt;element name="InventRefTransId" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_InventRefTransId" minOccurs="0"/>
 *         &lt;element name="InventRefType" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdEnum_InventRefType" minOccurs="0"/>
 *         &lt;element name="InventTransId" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_TradeInventTransId" minOccurs="0"/>
 *         &lt;element name="InvoiceDate" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_TransDate"/>
 *         &lt;element name="InvoiceId" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_CustInvoiceId"/>
 *         &lt;element name="ItemCodeId" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_IntrastatItemCodeId" minOccurs="0"/>
 *         &lt;element name="ItemId" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdUnion_AxdExtType_ItemId_AxdType_ExtCodeValue" minOccurs="0"/>
 *         &lt;element name="ItemName" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_ItemName" minOccurs="0"/>
 *         &lt;element name="LedgerDimension" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdType_DefaultAccount" minOccurs="0"/>
 *         &lt;element name="LineAmount" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_AmountCur" minOccurs="0"/>
 *         &lt;element name="LineAmountInclTax" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_LineAmount" minOccurs="0"/>
 *         &lt;element name="LineAmountMST" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_AmountMST" minOccurs="0"/>
 *         &lt;element name="LineAmountPreSubOfDiscPercentInclTax" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_AmountCur" minOccurs="0"/>
 *         &lt;element name="LineAmountTax" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_LineAmountTax" minOccurs="0"/>
 *         &lt;element name="LineAmountTaxMST" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_LineAmountTaxMST" minOccurs="0"/>
 *         &lt;element name="LineDisc" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_SalesLineDisc" minOccurs="0"/>
 *         &lt;element name="LineHeader" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_LineHeader" minOccurs="0"/>
 *         &lt;element name="LineNum" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_LineNum" minOccurs="0"/>
 *         &lt;element name="LinePercent" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_SalesLinePercent" minOccurs="0"/>
 *         &lt;element name="MultiLnDisc" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_SalesMultiLnDisc" minOccurs="0"/>
 *         &lt;element name="MultiLnPercent" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_SalesMultiLnPercent" minOccurs="0"/>
 *         &lt;element name="Name" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_ItemFreeTxtBase" minOccurs="0"/>
 *         &lt;element name="NGPCodesTable_FR" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_NGP_FR" minOccurs="0"/>
 *         &lt;element name="NumberSequenceGroup" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_NumberSequenceGroupId" minOccurs="0"/>
 *         &lt;element name="OrigCountryRegionId" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdUnion_AxdExtType_ItemOrigCountryRegionId_AxdType_ExtCodeValue" minOccurs="0"/>
 *         &lt;element name="OrigSalesId" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_SalesIdOrig" minOccurs="0"/>
 *         &lt;element name="OrigState" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdUnion_AxdExtType_ItemOrigStateId_AxdType_ExtCodeValue" minOccurs="0"/>
 *         &lt;element name="PartDelivery" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_PartDelivery" minOccurs="0"/>
 *         &lt;element name="Port" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_IntrastatPortId" minOccurs="0"/>
 *         &lt;element name="PriceUnit" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_PriceUnit" minOccurs="0"/>
 *         &lt;element name="Qty" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_SalesInvoicedQty" minOccurs="0"/>
 *         &lt;element name="QtyPhysical" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_SalesQty" minOccurs="0"/>
 *         &lt;element name="RecId" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_RecId" minOccurs="0"/>
 *         &lt;element name="RecVersion" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_RecVersion" minOccurs="0"/>
 *         &lt;element name="Remain" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_SalesQty" minOccurs="0"/>
 *         &lt;element name="ReturnArrivalDate" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_ReturnArrivalDate" minOccurs="0"/>
 *         &lt;element name="ReturnClosedDate" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_ReturnClosedDate" minOccurs="0"/>
 *         &lt;element name="ReturnDispositionCodeId" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_ReturnDispositionCodeId" minOccurs="0"/>
 *         &lt;element name="ReverseChargeApplies_UK" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_ReverseChargeApplies_UK" minOccurs="0"/>
 *         &lt;element name="ReversedRecId" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_RefRecId" minOccurs="0"/>
 *         &lt;element name="SalesCategory" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdEntityKey_EcoResCategory" minOccurs="0"/>
 *         &lt;element name="SalesGroup" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_CommissSalesGroup" minOccurs="0"/>
 *         &lt;element name="SalesId" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_SalesId" minOccurs="0"/>
 *         &lt;element name="SalesMarkup" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_SalesMarkup" minOccurs="0"/>
 *         &lt;element name="SalesPrice" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_SalesPrice" minOccurs="0"/>
 *         &lt;element name="SalesUnit" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdUnion_AxdExtType_SalesUnit_AxdType_ExtCodeValue" minOccurs="0"/>
 *         &lt;element name="SourceDocumentLine" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_RefRecId" minOccurs="0"/>
 *         &lt;element name="StatLineAmountMST" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_IntrastatLineAmountMST" minOccurs="0"/>
 *         &lt;element name="StatProcId" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_IntrastatProcId" minOccurs="0"/>
 *         &lt;element name="StockedProduct" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_TradeStockedProduct" minOccurs="0"/>
 *         &lt;element name="SumLineDisc" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_SalesSumLineDiscAmount" minOccurs="0"/>
 *         &lt;element name="SumLineDiscMST" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_SalesSumLineDiscAmountMST" minOccurs="0"/>
 *         &lt;element name="TaxAmount" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_TaxAmountCur" minOccurs="0"/>
 *         &lt;element name="TaxAmountMST" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_TaxAmount" minOccurs="0"/>
 *         &lt;element name="TaxAutogenerated" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_TaxAutoGenerated" minOccurs="0"/>
 *         &lt;element name="TaxGroup" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_TaxGroup" minOccurs="0"/>
 *         &lt;element name="TaxItemGroup" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_TaxItemGroup" minOccurs="0"/>
 *         &lt;element name="TaxWithholdGroup_TH" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_TaxWithholdGroup" minOccurs="0"/>
 *         &lt;element name="TaxWithholdItemGroupHeading_TH" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_TaxWithholdItemGroup_TH" minOccurs="0"/>
 *         &lt;element name="TaxWriteCode" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_TaxWriteCode" minOccurs="0"/>
 *         &lt;element name="TransactionCode" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_IntrastatTransactionCodeId" minOccurs="0"/>
 *         &lt;element name="Transport" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_IntrastatTransport" minOccurs="0"/>
 *         &lt;element name="Weight" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdExtType_Weight" minOccurs="0"/>
 *         &lt;element name="SalesLine" type="{http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv}AxdEntity_SalesLine" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="class" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" fixed="entity" />
 *       &lt;attribute name="action" type="{http://schemas.microsoft.com/dynamics/2008/01/sharedtypes}AxdEnum_AxdEntityAction" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AxdEntity_CustInvoiceTrans", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", propOrder = {
    "amountDiscAmount",
    "amountDiscPercentInclTax",
    "assetBookId",
    "assetId",
    "commissAmountCur",
    "commissAmountMST",
    "commissCalc",
    "countryRegionOfShipment",
    "currencyCode",
    "customerLineNum",
    "deliveryType",
    "discAmount",
    "discPercent",
    "dlvDate",
    "eInvoiceAccountCode",
    "externalItemId",
    "interCompanyInventTransId",
    "intrastatDispatchId",
    "inventDimId",
    "inventQty",
    "inventRefId",
    "inventRefTransId",
    "inventRefType",
    "inventTransId",
    "invoiceDate",
    "invoiceId",
    "itemCodeId",
    "itemId",
    "itemName",
    "ledgerDimension",
    "lineAmount",
    "lineAmountInclTax",
    "lineAmountMST",
    "lineAmountPreSubOfDiscPercentInclTax",
    "lineAmountTax",
    "lineAmountTaxMST",
    "lineDisc",
    "lineHeader",
    "lineNum",
    "linePercent",
    "multiLnDisc",
    "multiLnPercent",
    "name",
    "ngpCodesTableFR",
    "numberSequenceGroup",
    "origCountryRegionId",
    "origSalesId",
    "origState",
    "partDelivery",
    "port",
    "priceUnit",
    "qty",
    "qtyPhysical",
    "recId",
    "recVersion",
    "remain",
    "returnArrivalDate",
    "returnClosedDate",
    "returnDispositionCodeId",
    "reverseChargeAppliesUK",
    "reversedRecId",
    "salesCategory",
    "salesGroup",
    "salesId",
    "salesMarkup",
    "salesPrice",
    "salesUnit",
    "sourceDocumentLine",
    "statLineAmountMST",
    "statProcId",
    "stockedProduct",
    "sumLineDisc",
    "sumLineDiscMST",
    "taxAmount",
    "taxAmountMST",
    "taxAutogenerated",
    "taxGroup",
    "taxItemGroup",
    "taxWithholdGroupTH",
    "taxWithholdItemGroupHeadingTH",
    "taxWriteCode",
    "transactionCode",
    "transport",
    "weight",
    "salesLine"
})
public class AxdEntityCustInvoiceTrans {

    @XmlElementRef(name = "AmountDiscAmount", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<BigDecimal> amountDiscAmount;
    @XmlElementRef(name = "AmountDiscPercentInclTax", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<BigDecimal> amountDiscPercentInclTax;
    @XmlElementRef(name = "AssetBookId", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> assetBookId;
    @XmlElementRef(name = "AssetId", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> assetId;
    @XmlElementRef(name = "CommissAmountCur", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<BigDecimal> commissAmountCur;
    @XmlElementRef(name = "CommissAmountMST", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<BigDecimal> commissAmountMST;
    @XmlElementRef(name = "CommissCalc", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<AxdExtTypeCommissCalc> commissCalc;
    @XmlElementRef(name = "CountryRegionOfShipment", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> countryRegionOfShipment;
    @XmlElementRef(name = "CurrencyCode", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> currencyCode;
    @XmlElementRef(name = "CustomerLineNum", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<Integer> customerLineNum;
    @XmlElementRef(name = "DeliveryType", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<AxdExtTypeTradeLineDlvTypeId> deliveryType;
    @XmlElementRef(name = "DiscAmount", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<BigDecimal> discAmount;
    @XmlElementRef(name = "DiscPercent", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<BigDecimal> discPercent;
    @XmlElementRef(name = "DlvDate", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> dlvDate;
    @XmlElementRef(name = "EInvoiceAccountCode", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> eInvoiceAccountCode;
    @XmlElementRef(name = "ExternalItemId", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> externalItemId;
    @XmlElementRef(name = "InterCompanyInventTransId", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> interCompanyInventTransId;
    @XmlElementRef(name = "IntrastatDispatchId", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> intrastatDispatchId;
    @XmlElementRef(name = "InventDimId", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> inventDimId;
    @XmlElementRef(name = "InventQty", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<BigDecimal> inventQty;
    @XmlElementRef(name = "InventRefId", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> inventRefId;
    @XmlElementRef(name = "InventRefTransId", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> inventRefTransId;
    @XmlElementRef(name = "InventRefType", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<AxdEnumInventRefType> inventRefType;
    @XmlElementRef(name = "InventTransId", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> inventTransId;
    @XmlElement(name = "InvoiceDate", required = true)
    protected XMLGregorianCalendar invoiceDate;
    @XmlElement(name = "InvoiceId", required = true)
    protected String invoiceId;
    @XmlElementRef(name = "ItemCodeId", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> itemCodeId;
    @XmlElementRef(name = "ItemId", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> itemId;
    @XmlElementRef(name = "ItemName", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> itemName;
    @XmlElementRef(name = "LedgerDimension", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<AxdTypeDefaultAccount> ledgerDimension;
    @XmlElementRef(name = "LineAmount", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<BigDecimal> lineAmount;
    @XmlElementRef(name = "LineAmountInclTax", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<BigDecimal> lineAmountInclTax;
    @XmlElementRef(name = "LineAmountMST", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<BigDecimal> lineAmountMST;
    @XmlElementRef(name = "LineAmountPreSubOfDiscPercentInclTax", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<BigDecimal> lineAmountPreSubOfDiscPercentInclTax;
    @XmlElementRef(name = "LineAmountTax", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<BigDecimal> lineAmountTax;
    @XmlElementRef(name = "LineAmountTaxMST", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<BigDecimal> lineAmountTaxMST;
    @XmlElementRef(name = "LineDisc", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<BigDecimal> lineDisc;
    @XmlElementRef(name = "LineHeader", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> lineHeader;
    @XmlElementRef(name = "LineNum", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<BigDecimal> lineNum;
    @XmlElementRef(name = "LinePercent", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<BigDecimal> linePercent;
    @XmlElementRef(name = "MultiLnDisc", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<BigDecimal> multiLnDisc;
    @XmlElementRef(name = "MultiLnPercent", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<BigDecimal> multiLnPercent;
    @XmlElementRef(name = "Name", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> name;
    @XmlElementRef(name = "NGPCodesTable_FR", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<Integer> ngpCodesTableFR;
    @XmlElementRef(name = "NumberSequenceGroup", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> numberSequenceGroup;
    @XmlElementRef(name = "OrigCountryRegionId", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> origCountryRegionId;
    @XmlElementRef(name = "OrigSalesId", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> origSalesId;
    @XmlElementRef(name = "OrigState", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> origState;
    @XmlElementRef(name = "PartDelivery", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<AxdExtTypePartDelivery> partDelivery;
    @XmlElementRef(name = "Port", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> port;
    @XmlElementRef(name = "PriceUnit", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<BigDecimal> priceUnit;
    @XmlElementRef(name = "Qty", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<BigDecimal> qty;
    @XmlElementRef(name = "QtyPhysical", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<BigDecimal> qtyPhysical;
    @XmlElementRef(name = "RecId", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<Long> recId;
    @XmlElementRef(name = "RecVersion", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<Integer> recVersion;
    @XmlElementRef(name = "Remain", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<BigDecimal> remain;
    @XmlElementRef(name = "ReturnArrivalDate", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> returnArrivalDate;
    @XmlElementRef(name = "ReturnClosedDate", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> returnClosedDate;
    @XmlElementRef(name = "ReturnDispositionCodeId", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> returnDispositionCodeId;
    @XmlElementRef(name = "ReverseChargeApplies_UK", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<AxdExtTypeReverseChargeAppliesUK> reverseChargeAppliesUK;
    @XmlElementRef(name = "ReversedRecId", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<Long> reversedRecId;
    @XmlElementRef(name = "SalesCategory", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<AxdEntityKeyEcoResCategory> salesCategory;
    @XmlElementRef(name = "SalesGroup", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> salesGroup;
    @XmlElementRef(name = "SalesId", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> salesId;
    @XmlElementRef(name = "SalesMarkup", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<BigDecimal> salesMarkup;
    @XmlElementRef(name = "SalesPrice", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<BigDecimal> salesPrice;
    @XmlElementRef(name = "SalesUnit", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> salesUnit;
    @XmlElementRef(name = "SourceDocumentLine", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<Long> sourceDocumentLine;
    @XmlElementRef(name = "StatLineAmountMST", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<BigDecimal> statLineAmountMST;
    @XmlElementRef(name = "StatProcId", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> statProcId;
    @XmlElementRef(name = "StockedProduct", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<AxdExtTypeTradeStockedProduct> stockedProduct;
    @XmlElementRef(name = "SumLineDisc", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<BigDecimal> sumLineDisc;
    @XmlElementRef(name = "SumLineDiscMST", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<BigDecimal> sumLineDiscMST;
    @XmlElementRef(name = "TaxAmount", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<BigDecimal> taxAmount;
    @XmlElementRef(name = "TaxAmountMST", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<BigDecimal> taxAmountMST;
    @XmlElementRef(name = "TaxAutogenerated", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<AxdExtTypeTaxAutoGenerated> taxAutogenerated;
    @XmlElementRef(name = "TaxGroup", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> taxGroup;
    @XmlElementRef(name = "TaxItemGroup", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> taxItemGroup;
    @XmlElementRef(name = "TaxWithholdGroup_TH", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> taxWithholdGroupTH;
    @XmlElementRef(name = "TaxWithholdItemGroupHeading_TH", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> taxWithholdItemGroupHeadingTH;
    @XmlElementRef(name = "TaxWriteCode", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> taxWriteCode;
    @XmlElementRef(name = "TransactionCode", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> transactionCode;
    @XmlElementRef(name = "Transport", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<String> transport;
    @XmlElementRef(name = "Weight", namespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/MDS_ITGSCustInv", type = JAXBElement.class)
    protected JAXBElement<BigDecimal> weight;
    @XmlElement(name = "SalesLine")
    protected List<AxdEntitySalesLine> salesLine;
    @XmlAttribute(name = "class", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String clazz;
    @XmlAttribute(name = "action")
    protected AxdEnumAxdEntityAction action;

    /**
     * Gets the value of the amountDiscAmount property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getAmountDiscAmount() {
        return amountDiscAmount;
    }

    /**
     * Sets the value of the amountDiscAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setAmountDiscAmount(JAXBElement<BigDecimal> value) {
        this.amountDiscAmount = value;
    }

    /**
     * Gets the value of the amountDiscPercentInclTax property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getAmountDiscPercentInclTax() {
        return amountDiscPercentInclTax;
    }

    /**
     * Sets the value of the amountDiscPercentInclTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setAmountDiscPercentInclTax(JAXBElement<BigDecimal> value) {
        this.amountDiscPercentInclTax = value;
    }

    /**
     * Gets the value of the assetBookId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAssetBookId() {
        return assetBookId;
    }

    /**
     * Sets the value of the assetBookId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAssetBookId(JAXBElement<String> value) {
        this.assetBookId = value;
    }

    /**
     * Gets the value of the assetId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAssetId() {
        return assetId;
    }

    /**
     * Sets the value of the assetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAssetId(JAXBElement<String> value) {
        this.assetId = value;
    }

    /**
     * Gets the value of the commissAmountCur property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getCommissAmountCur() {
        return commissAmountCur;
    }

    /**
     * Sets the value of the commissAmountCur property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setCommissAmountCur(JAXBElement<BigDecimal> value) {
        this.commissAmountCur = value;
    }

    /**
     * Gets the value of the commissAmountMST property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getCommissAmountMST() {
        return commissAmountMST;
    }

    /**
     * Sets the value of the commissAmountMST property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setCommissAmountMST(JAXBElement<BigDecimal> value) {
        this.commissAmountMST = value;
    }

    /**
     * Gets the value of the commissCalc property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AxdExtTypeCommissCalc }{@code >}
     *     
     */
    public JAXBElement<AxdExtTypeCommissCalc> getCommissCalc() {
        return commissCalc;
    }

    /**
     * Sets the value of the commissCalc property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AxdExtTypeCommissCalc }{@code >}
     *     
     */
    public void setCommissCalc(JAXBElement<AxdExtTypeCommissCalc> value) {
        this.commissCalc = value;
    }

    /**
     * Gets the value of the countryRegionOfShipment property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCountryRegionOfShipment() {
        return countryRegionOfShipment;
    }

    /**
     * Sets the value of the countryRegionOfShipment property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCountryRegionOfShipment(JAXBElement<String> value) {
        this.countryRegionOfShipment = value;
    }

    /**
     * Gets the value of the currencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCurrencyCode() {
        return currencyCode;
    }

    /**
     * Sets the value of the currencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCurrencyCode(JAXBElement<String> value) {
        this.currencyCode = value;
    }

    /**
     * Gets the value of the customerLineNum property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getCustomerLineNum() {
        return customerLineNum;
    }

    /**
     * Sets the value of the customerLineNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setCustomerLineNum(JAXBElement<Integer> value) {
        this.customerLineNum = value;
    }

    /**
     * Gets the value of the deliveryType property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AxdExtTypeTradeLineDlvTypeId }{@code >}
     *     
     */
    public JAXBElement<AxdExtTypeTradeLineDlvTypeId> getDeliveryType() {
        return deliveryType;
    }

    /**
     * Sets the value of the deliveryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AxdExtTypeTradeLineDlvTypeId }{@code >}
     *     
     */
    public void setDeliveryType(JAXBElement<AxdExtTypeTradeLineDlvTypeId> value) {
        this.deliveryType = value;
    }

    /**
     * Gets the value of the discAmount property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getDiscAmount() {
        return discAmount;
    }

    /**
     * Sets the value of the discAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setDiscAmount(JAXBElement<BigDecimal> value) {
        this.discAmount = value;
    }

    /**
     * Gets the value of the discPercent property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getDiscPercent() {
        return discPercent;
    }

    /**
     * Sets the value of the discPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setDiscPercent(JAXBElement<BigDecimal> value) {
        this.discPercent = value;
    }

    /**
     * Gets the value of the dlvDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getDlvDate() {
        return dlvDate;
    }

    /**
     * Sets the value of the dlvDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setDlvDate(JAXBElement<XMLGregorianCalendar> value) {
        this.dlvDate = value;
    }

    /**
     * Gets the value of the eInvoiceAccountCode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getEInvoiceAccountCode() {
        return eInvoiceAccountCode;
    }

    /**
     * Sets the value of the eInvoiceAccountCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setEInvoiceAccountCode(JAXBElement<String> value) {
        this.eInvoiceAccountCode = value;
    }

    /**
     * Gets the value of the externalItemId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getExternalItemId() {
        return externalItemId;
    }

    /**
     * Sets the value of the externalItemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setExternalItemId(JAXBElement<String> value) {
        this.externalItemId = value;
    }

    /**
     * Gets the value of the interCompanyInventTransId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getInterCompanyInventTransId() {
        return interCompanyInventTransId;
    }

    /**
     * Sets the value of the interCompanyInventTransId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setInterCompanyInventTransId(JAXBElement<String> value) {
        this.interCompanyInventTransId = value;
    }

    /**
     * Gets the value of the intrastatDispatchId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getIntrastatDispatchId() {
        return intrastatDispatchId;
    }

    /**
     * Sets the value of the intrastatDispatchId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setIntrastatDispatchId(JAXBElement<String> value) {
        this.intrastatDispatchId = value;
    }

    /**
     * Gets the value of the inventDimId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getInventDimId() {
        return inventDimId;
    }

    /**
     * Sets the value of the inventDimId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setInventDimId(JAXBElement<String> value) {
        this.inventDimId = value;
    }

    /**
     * Gets the value of the inventQty property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getInventQty() {
        return inventQty;
    }

    /**
     * Sets the value of the inventQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setInventQty(JAXBElement<BigDecimal> value) {
        this.inventQty = value;
    }

    /**
     * Gets the value of the inventRefId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getInventRefId() {
        return inventRefId;
    }

    /**
     * Sets the value of the inventRefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setInventRefId(JAXBElement<String> value) {
        this.inventRefId = value;
    }

    /**
     * Gets the value of the inventRefTransId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getInventRefTransId() {
        return inventRefTransId;
    }

    /**
     * Sets the value of the inventRefTransId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setInventRefTransId(JAXBElement<String> value) {
        this.inventRefTransId = value;
    }

    /**
     * Gets the value of the inventRefType property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AxdEnumInventRefType }{@code >}
     *     
     */
    public JAXBElement<AxdEnumInventRefType> getInventRefType() {
        return inventRefType;
    }

    /**
     * Sets the value of the inventRefType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AxdEnumInventRefType }{@code >}
     *     
     */
    public void setInventRefType(JAXBElement<AxdEnumInventRefType> value) {
        this.inventRefType = value;
    }

    /**
     * Gets the value of the inventTransId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getInventTransId() {
        return inventTransId;
    }

    /**
     * Sets the value of the inventTransId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setInventTransId(JAXBElement<String> value) {
        this.inventTransId = value;
    }

    /**
     * Gets the value of the invoiceDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getInvoiceDate() {
        return invoiceDate;
    }

    /**
     * Sets the value of the invoiceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInvoiceDate(XMLGregorianCalendar value) {
        this.invoiceDate = value;
    }

    /**
     * Gets the value of the invoiceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoiceId() {
        return invoiceId;
    }

    /**
     * Sets the value of the invoiceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoiceId(String value) {
        this.invoiceId = value;
    }

    /**
     * Gets the value of the itemCodeId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getItemCodeId() {
        return itemCodeId;
    }

    /**
     * Sets the value of the itemCodeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setItemCodeId(JAXBElement<String> value) {
        this.itemCodeId = value;
    }

    /**
     * Gets the value of the itemId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getItemId() {
        return itemId;
    }

    /**
     * Sets the value of the itemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setItemId(JAXBElement<String> value) {
        this.itemId = value;
    }

    /**
     * Gets the value of the itemName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getItemName() {
        return itemName;
    }

    /**
     * Sets the value of the itemName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setItemName(JAXBElement<String> value) {
        this.itemName = value;
    }

    /**
     * Gets the value of the ledgerDimension property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AxdTypeDefaultAccount }{@code >}
     *     
     */
    public JAXBElement<AxdTypeDefaultAccount> getLedgerDimension() {
        return ledgerDimension;
    }

    /**
     * Sets the value of the ledgerDimension property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AxdTypeDefaultAccount }{@code >}
     *     
     */
    public void setLedgerDimension(JAXBElement<AxdTypeDefaultAccount> value) {
        this.ledgerDimension = value;
    }

    /**
     * Gets the value of the lineAmount property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getLineAmount() {
        return lineAmount;
    }

    /**
     * Sets the value of the lineAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setLineAmount(JAXBElement<BigDecimal> value) {
        this.lineAmount = value;
    }

    /**
     * Gets the value of the lineAmountInclTax property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getLineAmountInclTax() {
        return lineAmountInclTax;
    }

    /**
     * Sets the value of the lineAmountInclTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setLineAmountInclTax(JAXBElement<BigDecimal> value) {
        this.lineAmountInclTax = value;
    }

    /**
     * Gets the value of the lineAmountMST property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getLineAmountMST() {
        return lineAmountMST;
    }

    /**
     * Sets the value of the lineAmountMST property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setLineAmountMST(JAXBElement<BigDecimal> value) {
        this.lineAmountMST = value;
    }

    /**
     * Gets the value of the lineAmountPreSubOfDiscPercentInclTax property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getLineAmountPreSubOfDiscPercentInclTax() {
        return lineAmountPreSubOfDiscPercentInclTax;
    }

    /**
     * Sets the value of the lineAmountPreSubOfDiscPercentInclTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setLineAmountPreSubOfDiscPercentInclTax(JAXBElement<BigDecimal> value) {
        this.lineAmountPreSubOfDiscPercentInclTax = value;
    }

    /**
     * Gets the value of the lineAmountTax property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getLineAmountTax() {
        return lineAmountTax;
    }

    /**
     * Sets the value of the lineAmountTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setLineAmountTax(JAXBElement<BigDecimal> value) {
        this.lineAmountTax = value;
    }

    /**
     * Gets the value of the lineAmountTaxMST property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getLineAmountTaxMST() {
        return lineAmountTaxMST;
    }

    /**
     * Sets the value of the lineAmountTaxMST property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setLineAmountTaxMST(JAXBElement<BigDecimal> value) {
        this.lineAmountTaxMST = value;
    }

    /**
     * Gets the value of the lineDisc property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getLineDisc() {
        return lineDisc;
    }

    /**
     * Sets the value of the lineDisc property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setLineDisc(JAXBElement<BigDecimal> value) {
        this.lineDisc = value;
    }

    /**
     * Gets the value of the lineHeader property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLineHeader() {
        return lineHeader;
    }

    /**
     * Sets the value of the lineHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLineHeader(JAXBElement<String> value) {
        this.lineHeader = value;
    }

    /**
     * Gets the value of the lineNum property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getLineNum() {
        return lineNum;
    }

    /**
     * Sets the value of the lineNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setLineNum(JAXBElement<BigDecimal> value) {
        this.lineNum = value;
    }

    /**
     * Gets the value of the linePercent property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getLinePercent() {
        return linePercent;
    }

    /**
     * Sets the value of the linePercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setLinePercent(JAXBElement<BigDecimal> value) {
        this.linePercent = value;
    }

    /**
     * Gets the value of the multiLnDisc property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getMultiLnDisc() {
        return multiLnDisc;
    }

    /**
     * Sets the value of the multiLnDisc property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setMultiLnDisc(JAXBElement<BigDecimal> value) {
        this.multiLnDisc = value;
    }

    /**
     * Gets the value of the multiLnPercent property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getMultiLnPercent() {
        return multiLnPercent;
    }

    /**
     * Sets the value of the multiLnPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setMultiLnPercent(JAXBElement<BigDecimal> value) {
        this.multiLnPercent = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setName(JAXBElement<String> value) {
        this.name = value;
    }

    /**
     * Gets the value of the ngpCodesTableFR property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getNGPCodesTableFR() {
        return ngpCodesTableFR;
    }

    /**
     * Sets the value of the ngpCodesTableFR property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setNGPCodesTableFR(JAXBElement<Integer> value) {
        this.ngpCodesTableFR = value;
    }

    /**
     * Gets the value of the numberSequenceGroup property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getNumberSequenceGroup() {
        return numberSequenceGroup;
    }

    /**
     * Sets the value of the numberSequenceGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setNumberSequenceGroup(JAXBElement<String> value) {
        this.numberSequenceGroup = value;
    }

    /**
     * Gets the value of the origCountryRegionId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getOrigCountryRegionId() {
        return origCountryRegionId;
    }

    /**
     * Sets the value of the origCountryRegionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setOrigCountryRegionId(JAXBElement<String> value) {
        this.origCountryRegionId = value;
    }

    /**
     * Gets the value of the origSalesId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getOrigSalesId() {
        return origSalesId;
    }

    /**
     * Sets the value of the origSalesId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setOrigSalesId(JAXBElement<String> value) {
        this.origSalesId = value;
    }

    /**
     * Gets the value of the origState property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getOrigState() {
        return origState;
    }

    /**
     * Sets the value of the origState property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setOrigState(JAXBElement<String> value) {
        this.origState = value;
    }

    /**
     * Gets the value of the partDelivery property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AxdExtTypePartDelivery }{@code >}
     *     
     */
    public JAXBElement<AxdExtTypePartDelivery> getPartDelivery() {
        return partDelivery;
    }

    /**
     * Sets the value of the partDelivery property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AxdExtTypePartDelivery }{@code >}
     *     
     */
    public void setPartDelivery(JAXBElement<AxdExtTypePartDelivery> value) {
        this.partDelivery = value;
    }

    /**
     * Gets the value of the port property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPort() {
        return port;
    }

    /**
     * Sets the value of the port property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPort(JAXBElement<String> value) {
        this.port = value;
    }

    /**
     * Gets the value of the priceUnit property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getPriceUnit() {
        return priceUnit;
    }

    /**
     * Sets the value of the priceUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setPriceUnit(JAXBElement<BigDecimal> value) {
        this.priceUnit = value;
    }

    /**
     * Gets the value of the qty property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getQty() {
        return qty;
    }

    /**
     * Sets the value of the qty property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setQty(JAXBElement<BigDecimal> value) {
        this.qty = value;
    }

    /**
     * Gets the value of the qtyPhysical property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getQtyPhysical() {
        return qtyPhysical;
    }

    /**
     * Sets the value of the qtyPhysical property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setQtyPhysical(JAXBElement<BigDecimal> value) {
        this.qtyPhysical = value;
    }

    /**
     * Gets the value of the recId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public JAXBElement<Long> getRecId() {
        return recId;
    }

    /**
     * Sets the value of the recId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public void setRecId(JAXBElement<Long> value) {
        this.recId = value;
    }

    /**
     * Gets the value of the recVersion property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getRecVersion() {
        return recVersion;
    }

    /**
     * Sets the value of the recVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setRecVersion(JAXBElement<Integer> value) {
        this.recVersion = value;
    }

    /**
     * Gets the value of the remain property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getRemain() {
        return remain;
    }

    /**
     * Sets the value of the remain property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setRemain(JAXBElement<BigDecimal> value) {
        this.remain = value;
    }

    /**
     * Gets the value of the returnArrivalDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getReturnArrivalDate() {
        return returnArrivalDate;
    }

    /**
     * Sets the value of the returnArrivalDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setReturnArrivalDate(JAXBElement<XMLGregorianCalendar> value) {
        this.returnArrivalDate = value;
    }

    /**
     * Gets the value of the returnClosedDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getReturnClosedDate() {
        return returnClosedDate;
    }

    /**
     * Sets the value of the returnClosedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setReturnClosedDate(JAXBElement<XMLGregorianCalendar> value) {
        this.returnClosedDate = value;
    }

    /**
     * Gets the value of the returnDispositionCodeId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getReturnDispositionCodeId() {
        return returnDispositionCodeId;
    }

    /**
     * Sets the value of the returnDispositionCodeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setReturnDispositionCodeId(JAXBElement<String> value) {
        this.returnDispositionCodeId = value;
    }

    /**
     * Gets the value of the reverseChargeAppliesUK property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AxdExtTypeReverseChargeAppliesUK }{@code >}
     *     
     */
    public JAXBElement<AxdExtTypeReverseChargeAppliesUK> getReverseChargeAppliesUK() {
        return reverseChargeAppliesUK;
    }

    /**
     * Sets the value of the reverseChargeAppliesUK property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AxdExtTypeReverseChargeAppliesUK }{@code >}
     *     
     */
    public void setReverseChargeAppliesUK(JAXBElement<AxdExtTypeReverseChargeAppliesUK> value) {
        this.reverseChargeAppliesUK = value;
    }

    /**
     * Gets the value of the reversedRecId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public JAXBElement<Long> getReversedRecId() {
        return reversedRecId;
    }

    /**
     * Sets the value of the reversedRecId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public void setReversedRecId(JAXBElement<Long> value) {
        this.reversedRecId = value;
    }

    /**
     * Gets the value of the salesCategory property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AxdEntityKeyEcoResCategory }{@code >}
     *     
     */
    public JAXBElement<AxdEntityKeyEcoResCategory> getSalesCategory() {
        return salesCategory;
    }

    /**
     * Sets the value of the salesCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AxdEntityKeyEcoResCategory }{@code >}
     *     
     */
    public void setSalesCategory(JAXBElement<AxdEntityKeyEcoResCategory> value) {
        this.salesCategory = value;
    }

    /**
     * Gets the value of the salesGroup property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSalesGroup() {
        return salesGroup;
    }

    /**
     * Sets the value of the salesGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSalesGroup(JAXBElement<String> value) {
        this.salesGroup = value;
    }

    /**
     * Gets the value of the salesId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSalesId() {
        return salesId;
    }

    /**
     * Sets the value of the salesId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSalesId(JAXBElement<String> value) {
        this.salesId = value;
    }

    /**
     * Gets the value of the salesMarkup property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getSalesMarkup() {
        return salesMarkup;
    }

    /**
     * Sets the value of the salesMarkup property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setSalesMarkup(JAXBElement<BigDecimal> value) {
        this.salesMarkup = value;
    }

    /**
     * Gets the value of the salesPrice property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getSalesPrice() {
        return salesPrice;
    }

    /**
     * Sets the value of the salesPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setSalesPrice(JAXBElement<BigDecimal> value) {
        this.salesPrice = value;
    }

    /**
     * Gets the value of the salesUnit property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSalesUnit() {
        return salesUnit;
    }

    /**
     * Sets the value of the salesUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSalesUnit(JAXBElement<String> value) {
        this.salesUnit = value;
    }

    /**
     * Gets the value of the sourceDocumentLine property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public JAXBElement<Long> getSourceDocumentLine() {
        return sourceDocumentLine;
    }

    /**
     * Sets the value of the sourceDocumentLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public void setSourceDocumentLine(JAXBElement<Long> value) {
        this.sourceDocumentLine = value;
    }

    /**
     * Gets the value of the statLineAmountMST property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getStatLineAmountMST() {
        return statLineAmountMST;
    }

    /**
     * Sets the value of the statLineAmountMST property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setStatLineAmountMST(JAXBElement<BigDecimal> value) {
        this.statLineAmountMST = value;
    }

    /**
     * Gets the value of the statProcId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getStatProcId() {
        return statProcId;
    }

    /**
     * Sets the value of the statProcId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setStatProcId(JAXBElement<String> value) {
        this.statProcId = value;
    }

    /**
     * Gets the value of the stockedProduct property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AxdExtTypeTradeStockedProduct }{@code >}
     *     
     */
    public JAXBElement<AxdExtTypeTradeStockedProduct> getStockedProduct() {
        return stockedProduct;
    }

    /**
     * Sets the value of the stockedProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AxdExtTypeTradeStockedProduct }{@code >}
     *     
     */
    public void setStockedProduct(JAXBElement<AxdExtTypeTradeStockedProduct> value) {
        this.stockedProduct = value;
    }

    /**
     * Gets the value of the sumLineDisc property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getSumLineDisc() {
        return sumLineDisc;
    }

    /**
     * Sets the value of the sumLineDisc property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setSumLineDisc(JAXBElement<BigDecimal> value) {
        this.sumLineDisc = value;
    }

    /**
     * Gets the value of the sumLineDiscMST property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getSumLineDiscMST() {
        return sumLineDiscMST;
    }

    /**
     * Sets the value of the sumLineDiscMST property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setSumLineDiscMST(JAXBElement<BigDecimal> value) {
        this.sumLineDiscMST = value;
    }

    /**
     * Gets the value of the taxAmount property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getTaxAmount() {
        return taxAmount;
    }

    /**
     * Sets the value of the taxAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setTaxAmount(JAXBElement<BigDecimal> value) {
        this.taxAmount = value;
    }

    /**
     * Gets the value of the taxAmountMST property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getTaxAmountMST() {
        return taxAmountMST;
    }

    /**
     * Sets the value of the taxAmountMST property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setTaxAmountMST(JAXBElement<BigDecimal> value) {
        this.taxAmountMST = value;
    }

    /**
     * Gets the value of the taxAutogenerated property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AxdExtTypeTaxAutoGenerated }{@code >}
     *     
     */
    public JAXBElement<AxdExtTypeTaxAutoGenerated> getTaxAutogenerated() {
        return taxAutogenerated;
    }

    /**
     * Sets the value of the taxAutogenerated property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AxdExtTypeTaxAutoGenerated }{@code >}
     *     
     */
    public void setTaxAutogenerated(JAXBElement<AxdExtTypeTaxAutoGenerated> value) {
        this.taxAutogenerated = value;
    }

    /**
     * Gets the value of the taxGroup property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTaxGroup() {
        return taxGroup;
    }

    /**
     * Sets the value of the taxGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTaxGroup(JAXBElement<String> value) {
        this.taxGroup = value;
    }

    /**
     * Gets the value of the taxItemGroup property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTaxItemGroup() {
        return taxItemGroup;
    }

    /**
     * Sets the value of the taxItemGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTaxItemGroup(JAXBElement<String> value) {
        this.taxItemGroup = value;
    }

    /**
     * Gets the value of the taxWithholdGroupTH property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTaxWithholdGroupTH() {
        return taxWithholdGroupTH;
    }

    /**
     * Sets the value of the taxWithholdGroupTH property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTaxWithholdGroupTH(JAXBElement<String> value) {
        this.taxWithholdGroupTH = value;
    }

    /**
     * Gets the value of the taxWithholdItemGroupHeadingTH property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTaxWithholdItemGroupHeadingTH() {
        return taxWithholdItemGroupHeadingTH;
    }

    /**
     * Sets the value of the taxWithholdItemGroupHeadingTH property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTaxWithholdItemGroupHeadingTH(JAXBElement<String> value) {
        this.taxWithholdItemGroupHeadingTH = value;
    }

    /**
     * Gets the value of the taxWriteCode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTaxWriteCode() {
        return taxWriteCode;
    }

    /**
     * Sets the value of the taxWriteCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTaxWriteCode(JAXBElement<String> value) {
        this.taxWriteCode = value;
    }

    /**
     * Gets the value of the transactionCode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTransactionCode() {
        return transactionCode;
    }

    /**
     * Sets the value of the transactionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTransactionCode(JAXBElement<String> value) {
        this.transactionCode = value;
    }

    /**
     * Gets the value of the transport property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTransport() {
        return transport;
    }

    /**
     * Sets the value of the transport property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTransport(JAXBElement<String> value) {
        this.transport = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setWeight(JAXBElement<BigDecimal> value) {
        this.weight = value;
    }

    /**
     * Gets the value of the salesLine property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the salesLine property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSalesLine().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AxdEntitySalesLine }
     * 
     * 
     */
    public List<AxdEntitySalesLine> getSalesLine() {
        if (salesLine == null) {
            salesLine = new ArrayList<AxdEntitySalesLine>();
        }
        return this.salesLine;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClazz() {
        if (clazz == null) {
            return "entity";
        } else {
            return clazz;
        }
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClazz(String value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link AxdEnumAxdEntityAction }
     *     
     */
    public AxdEnumAxdEntityAction getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link AxdEnumAxdEntityAction }
     *     
     */
    public void setAction(AxdEnumAxdEntityAction value) {
        this.action = value;
    }

}
