//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.28 at 01:35:45 PM CET 
//


package com.tradedoubler.customerinvoice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * UTC timestamp:The UTC timestamp.
 * 
 * <p>Java class for AxdExtType_UTCTimestamp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AxdExtType_UTCTimestamp">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://schemas.microsoft.com/dynamics/2008/01/sharedtypes>AxdType_DateTime">
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AxdExtType_UTCTimestamp")
public class AxdExtTypeUTCTimestamp
    extends AxdTypeDateTime
{


}
