//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.28 at 01:35:45 PM CET 
//


package com.tradedoubler.customerinvoice;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AxdEnum_InventTransferShipUpdateQty.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AxdEnum_InventTransferShipUpdateQty">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ShipNow"/>
 *     &lt;enumeration value="All"/>
 *     &lt;enumeration value="ReservedQty"/>
 *     &lt;enumeration value="AvailableQty"/>
 *     &lt;enumeration value="PickedQty"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AxdEnum_InventTransferShipUpdateQty")
@XmlEnum
public enum AxdEnumInventTransferShipUpdateQty {

    @XmlEnumValue("ShipNow")
    SHIP_NOW("ShipNow"),
    @XmlEnumValue("All")
    ALL("All"),
    @XmlEnumValue("ReservedQty")
    RESERVED_QTY("ReservedQty"),
    @XmlEnumValue("AvailableQty")
    AVAILABLE_QTY("AvailableQty"),
    @XmlEnumValue("PickedQty")
    PICKED_QTY("PickedQty");
    private final String value;

    AxdEnumInventTransferShipUpdateQty(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AxdEnumInventTransferShipUpdateQty fromValue(String v) {
        for (AxdEnumInventTransferShipUpdateQty c: AxdEnumInventTransferShipUpdateQty.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
