//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.28 at 01:35:45 PM CET 
//


package com.tradedoubler.customerinvoice;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AxdEnum_ParmJobStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AxdEnum_ParmJobStatus">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Executed"/>
 *     &lt;enumeration value="ContainErrors"/>
 *     &lt;enumeration value="Waiting"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AxdEnum_ParmJobStatus")
@XmlEnum
public enum AxdEnumParmJobStatus {

    @XmlEnumValue("Executed")
    EXECUTED("Executed"),
    @XmlEnumValue("ContainErrors")
    CONTAIN_ERRORS("ContainErrors"),
    @XmlEnumValue("Waiting")
    WAITING("Waiting");
    private final String value;

    AxdEnumParmJobStatus(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AxdEnumParmJobStatus fromValue(String v) {
        for (AxdEnumParmJobStatus c: AxdEnumParmJobStatus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
