//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.28 at 01:35:45 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.microsoft.com/dynamics/2008/01/sharedtypes", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.tradedoubler.customerinvoice;
